apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-book-service
  template:
    metadata:
      labels:
        app: fastapi-book-service
    spec:
      containers:
        - name: fastapi-book-service
          image: fastapi-book-service:k8s
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:supersecret@postgres-service:5432/postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-book-service
spec:
  type: NodePort
  selector:
    app: fastapi-book-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
