apiVersion: v1
kind: Service
metadata:
  name: fastapi-book-service
  namespace: default
  labels:
    app: fastapi-book-service
spec:
  selector:
    app: fastapi-book-service
  ports:
    - name: http        
      port: 8000
      targetPort: 8000
  type: ClusterIP
